"""add language to posts

Revision ID: 049985903704
Revises: dde9ffa28423
Create Date: 2021-04-21 16:31:52.836877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '049985903704'
down_revision = 'dde9ffa28423'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
